name: JetStreamCompose

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/JetStreamCompose.yml'
      - 'JetStreamCompose/**'
  pull_request:
    paths:
      - '.github/workflows/JetStreamCompose.yml'
      - 'JetStreamCompose/**'

jobs:
  build:
    uses: ./.github/workflows/build-sample.yml
    with:
      path: JetStreamCompose